server:
  port: 8888
spring:
  application:
    name: spring-boot-grafana-integration
management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always